<a href="https://colab.research.google.com/github/akashrraj24/pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#dataset is from data frame
# collection of data in row column format

#dataframe
# row ,column format into python

# series are the building block of dataframe

# difference btw array and series

# array=> implict ,less memory, faster , n dimension (1d,2,3d.....)
# series=> explicit index,more memory,slower, 1 dimension
import numpy as np

In [ ]:
import pandas as pd
import numpy as np

a=np.arange(4,10)
s=pd.Series(a)
print(s)

print(s.ndim)
print(s.size)
print(s.shape)

print(s.head(3))
print(s.tail(3))

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64
1
6
(6,)
0    4
1    5
2    6
dtype: int64
3    7
4    8
5    9
dtype: int64

In [ ]:
# create  two series
a=pd.Series([4,5,6,7,8])
b=pd.Series([5,4,3,6,7])
print(a)
print(b)
d=pd.concat([a,b],ignore_index=True)   #concat is used to combine series
print(d)                               #add a parameter ignore index

0    4
1    5
2    6
3    7
4    8
dtype: int64
0    5
1    4
2    3
3    6
4    7
dtype: int64
0    4
1    5
2    6
3    7
4    8
5    5
6    4
7    3
8    6
9    7
dtype: int64

In [ ]:
e=a.add(b)
print(e)

e=a.sub(b)
print(e)

e=a.mul(b)
print(e)

e=a.div(b)
print(e)

0     9
1     9
2     9
3    13
4    15
dtype: int64
0   -1
1    1
2    3
3    1
4    1
dtype: int64
0    20
1    20
2    18
3    42
4    56
dtype: int64
0    0.800000
1    1.250000
2    2.000000
3    1.166667
4    1.142857
dtype: float64

In [ ]:
z=pd.Series([3,4,5,6],index=["a","b","c","d"])  # for custom index
z

a    3
b    4
c    5
d    6
dtype: int64

In [ ]:
d={"id":1,"age":54,"class":"ds"}
z=pd.Series(d)
z

id        1
age      54
class    ds
dtype: object

In [ ]:
z=pd.Series(4,index=[1,2,3,4])   #to store same value in position
z

1    4
2    4
3    4
4    4
dtype: int64

In [ ]:
z=pd.Series([1,2,3,4,5,6,7])
print(z)

z[3]
z[1:4]
z[[6,1,5]]  # to fetch multiple element use [[]](use double square brackets)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

6    7
1    2
5    6
dtype: int64

In [ ]:
#dataframe (2d)
#create dataframe from list

l=[1,2,3,4,5]

df=pd.DataFrame(l)

df.shape
df.size
df.ndim
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
#create dataframe from nested list
l=[["apple",102],["orange",48],["grapes",56]]
df=pd.DataFrame(l,columns=["fruits","price"])
df

   fruits  price
0   apple    102
1  orange     48
2  grapes     56

In [ ]:
#create a dataframe with id name location and add 4 rows
l=[[11,"akash","TVM"],[12,"nabil","TVM"],[13,"farhan","Tvm"],[14,"karthik","TVM"]]
df=pd.DataFrame(l,columns=["Id","Name","location"])
df
print(df.head(1))
print(df.tail(2))
df.head(2)

   Id   Name location
0  11  akash      TVM
   Id     Name location
2  13   farhan      Tvm
3  14  karthik      TVM

   Id   Name location
0  11  akash      TVM
1  12  nabil      TVM

In [ ]:
#using dictionary and list
d={"id":[1,2,3,4],"name":["Akash","Nabil","Farhan","Krthik"],"age":[20,21,22,20]}
df=pd.DataFrame(d)
df

   id    name  age
0   1   Akash   20
1   2   Nabil   21
2   3  Farhan   22
3   4  Krthik   20

In [6]:
import pandas as pd

#create dataframe from list of dictionay

l=[{"fruits":"apple","price":234},{"fruits":"orange","price":87},{"fruits":"grapes","price":90}]
df=pd.DataFrame(l)
df

   fruits  price
0   apple    234
1  orange     87
2  grapes     90

In [14]:
#creating dataframe using dictionary and series

d={"fruits":pd.Series(["apple","orange","mango"]),"price":pd.Series([3,4,5])}
df=pd.DataFrame(d)
df

   fruits  price
0   apple      3
1  orange      4
2   mango      5

In [18]:
# create data frame with id name age salary profession and add 5 values
d={"ID":pd.Series([1,2,3,4,5]),"Name":pd.Series(["Akash","Nabil","Farhan","Rihan","Adithyan"]),"Age":pd.Series([22,22,23,24,25]),"Salary":pd.Series([15000,16000,15000,14000,12000]),"Profession":pd.Series(["IT","Developer","Analyst","Java","Python"])}
df=pd.DataFrame(d)
df

df["location"]=["tvm","kochi","kollam","tvm","kochi"]
df

   ID      Name  Age  Salary Profession location
0   1     Akash   22   15000         IT      tvm
1   2     Nabil   22   16000  Developer    kochi
2   3    Farhan   23   15000    Analyst   kollam
3   4     Rihan   24   14000       Java      tvm
4   5  Adithyan   25   12000     Python    kochi

In [24]:
# to display  a specific column
df[['Salary','Name','location']]

   Salary      Name location
0   15000     Akash      tvm
1   16000     Nabil    kochi
2   15000    Farhan   kollam
3   14000     Rihan      tvm
4   12000  Adithyan    kochi